const questions = [
  // ===== GÉOGRAPHIE =====
  { theme: "Géographie", emoji: "🗺️", question: "Quelle est la capitale de l'Australie ?", hint: "Ce n'est ni Sydney ni Melbourne", answers: ["canberra"] },
  { theme: "Géographie", emoji: "🌍", question: "Quel est le plus grand pays du monde en superficie ?", hint: "Il s'étend sur deux continents", answers: ["russie", "russia"] },
  { theme: "Géographie", emoji: "🗼", question: "Dans quelle ville se trouve la Tour Eiffel ?", hint: "Capitale de la France", answers: ["paris"] },
  { theme: "Géographie", emoji: "🏔️", question: "Quel est le plus haut sommet du monde ?", hint: "Situé dans l'Himalaya", answers: ["everest", "mont everest"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel est l'océan le plus grand du monde ?", hint: "Il borde l'Asie et l'Amérique", answers: ["pacifique", "ocean pacifique"] },
  { theme: "Géographie", emoji: "🇧🇷", question: "Quelle est la capitale du Brésil ?", hint: "Ce n'est pas Rio de Janeiro", answers: ["brasilia", "brasília"] },
  { theme: "Géographie", emoji: "🌋", question: "Sur quelle île se trouve le volcan Etna ?", hint: "Grande île italienne", answers: ["sicile", "sicily"] },
  { theme: "Géographie", emoji: "🏜️", question: "Quel est le plus grand désert chaud du monde ?", hint: "En Afrique du Nord", answers: ["sahara"] },
  { theme: "Géographie", emoji: "🇯🇵", question: "Quelle est la capitale du Japon ?", hint: "Plus grande métropole du monde", answers: ["tokyo"] },
  { theme: "Géographie", emoji: "🌐", question: "Combien de continents y a-t-il sur Terre ?", hint: "La réponse classique", answers: ["7", "sept"] },
  { theme: "Géographie", emoji: "🇨🇳", question: "Quelle est la capitale de la Chine ?", hint: "Elle accueilli les JO 2008", answers: ["pekin", "pékin", "beijing"] },
  { theme: "Géographie", emoji: "🇮🇳", question: "Quelle est la capitale de l'Inde ?", hint: "Pas Mumbai ni Calcutta", answers: ["new delhi", "delhi"] },
  { theme: "Géographie", emoji: "🇩🇪", question: "Quelle est la capitale de l'Allemagne ?", hint: "Le mur est tombé en 1989", answers: ["berlin"] },
  { theme: "Géographie", emoji: "🇪🇸", question: "Quelle est la capitale de l'Espagne ?", hint: "Le Real et l'Atlético y jouent", answers: ["madrid"] },
  { theme: "Géographie", emoji: "🇮🇹", question: "Quelle est la capitale de l'Italie ?", hint: "La ville éternelle", answers: ["rome", "roma"] },
  { theme: "Géographie", emoji: "🇬🇧", question: "Quelle est la capitale du Royaume-Uni ?", hint: "Big Ben s'y trouve", answers: ["londres", "london"] },
  { theme: "Géographie", emoji: "🇰🇷", question: "Quelle est la capitale de la Corée du Sud ?", hint: "Samsung y est né", answers: ["seoul", "séoul"] },
  { theme: "Géographie", emoji: "🇲🇽", question: "Quelle est la capitale du Mexique ?", hint: "Ancienne capitale aztèque", answers: ["mexico", "mexico city", "ciudad de mexico"] },
  { theme: "Géographie", emoji: "🇦🇷", question: "Quelle est la capitale de l'Argentine ?", hint: "Messi y est né", answers: ["buenos aires"] },
  { theme: "Géographie", emoji: "🇷🇺", question: "Quelle est la capitale de la Russie ?", hint: "Le Kremlin s'y trouve", answers: ["moscou", "moscow", "moskva"] },
  { theme: "Géographie", emoji: "🇹🇷", question: "Quelle est la capitale de la Turquie ?", hint: "Ce n'est pas Istanbul", answers: ["ankara"] },
  { theme: "Géographie", emoji: "🇪🇬", question: "Quelle est la capitale de l'Égypte ?", hint: "Près des pyramides", answers: ["le caire", "cairo"] },
  { theme: "Géographie", emoji: "🇸🇦", question: "Quelle est la capitale de l'Arabie Saoudite ?", hint: "Commence par R", answers: ["riyad", "riyadh"] },
  { theme: "Géographie", emoji: "🇿🇦", question: "Quelle est la capitale administrative de l'Afrique du Sud ?", hint: "Trois capitales, la plus connue", answers: ["pretoria"] },
  { theme: "Géographie", emoji: "🇨🇦", question: "Quelle est la capitale du Canada ?", hint: "Ce n'est ni Toronto ni Montréal", answers: ["ottawa"] },
  { theme: "Géographie", emoji: "🇺🇸", question: "Quelle est la capitale des États-Unis ?", hint: "Le Capitole s'y trouve", answers: ["washington", "washington dc"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel est le plus long fleuve du monde ?", hint: "En Afrique du Nord ou en Amérique du Sud selon les mesures", answers: ["nil", "amazone", "nile"] },
  { theme: "Géographie", emoji: "🏔️", question: "Dans quel pays se trouve le mont Kilimandjaro ?", hint: "Pays d'Afrique de l'Est", answers: ["tanzanie", "tanzania"] },
  { theme: "Géographie", emoji: "🌍", question: "Quel est le pays le plus peuplé du monde ?", hint: "Depuis 2023", answers: ["inde", "india"] },
  { theme: "Géographie", emoji: "🏝️", question: "De combien d'îles est composé le Japon ?", hint: "Environ 6800", answers: ["6852", "6800", "environ 6800"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel détroit sépare l'Europe de l'Afrique ?", hint: "Entre Espagne et Maroc", answers: ["detroit de gibraltar", "gibraltar"] },
  { theme: "Géographie", emoji: "🗻", question: "Quelle est la plus haute montagne d'Europe ?", hint: "En Russie ou en France selon la définition", answers: ["mont blanc", "elbrouz", "elbrus"] },
  { theme: "Géographie", emoji: "🇵🇹", question: "Quelle est la capitale du Portugal ?", hint: "Au bord du Tage", answers: ["lisbonne", "lisbon", "lisboa"] },
  { theme: "Géographie", emoji: "🇨🇭", question: "Quelle est la capitale de la Suisse ?", hint: "Ce n'est ni Genève ni Zurich", answers: ["berne", "bern"] },
  { theme: "Géographie", emoji: "🇳🇱", question: "Quelle est la capitale des Pays-Bas ?", hint: "Pas La Haye", answers: ["amsterdam"] },
  { theme: "Géographie", emoji: "🇧🇪", question: "Quelle est la capitale de la Belgique ?", hint: "Siège de l'UE", answers: ["bruxelles", "brussels"] },
  { theme: "Géographie", emoji: "🇵🇱", question: "Quelle est la capitale de la Pologne ?", hint: "Sur la Vistule", answers: ["varsovie", "warsaw", "warszawa"] },
  { theme: "Géographie", emoji: "🌍", question: "Quel pays a la plus longue frontière terrestre du monde ?", hint: "Pays frontalier avec 14 nations", answers: ["chine", "china", "russie"] },
  { theme: "Géographie", emoji: "🏙️", question: "Dans quelle ville se trouve la statue de la Liberté ?", hint: "La Grande Pomme", answers: ["new york", "new york city", "nyc"] },
  { theme: "Géographie", emoji: "🇦🇺", question: "Quelle est la plus grande ville d'Australie ?", hint: "Pas la capitale", answers: ["sydney"] },
  { theme: "Géographie", emoji: "🗺️", question: "Combien de pays se partagent le continent africain ?", hint: "Plus de 50", answers: ["54", "cinquante-quatre"] },
  { theme: "Géographie", emoji: "🌊", question: "Quelle mer sépare l'Italie de la Croatie ?", hint: "Mer intérieure de la Méditerranée", answers: ["mer adriatique", "adriatique"] },
  { theme: "Géographie", emoji: "🏔️", question: "Quel est le plus petit pays du monde ?", hint: "Enclave dans Rome", answers: ["vatican", "saint-siege"] },
  { theme: "Géographie", emoji: "🌍", question: "Dans quel pays se trouve le lac Titicaca ?", hint: "Le plus haut lac navigable du monde, entre deux pays", answers: ["perou", "pérou", "bolivie"] },
  { theme: "Géographie", emoji: "🇸🇪", question: "Quelle est la capitale de la Suède ?", hint: "Abba y est né", answers: ["stockholm"] },
  { theme: "Géographie", emoji: "🇳🇴", question: "Quelle est la capitale de la Norvège ?", hint: "Ville des fjords", answers: ["oslo"] },
  { theme: "Géographie", emoji: "🇩🇰", question: "Quelle est la capitale du Danemark ?", hint: "La petite sirène y est", answers: ["copenhague", "copenhagen"] },
  { theme: "Géographie", emoji: "🇫🇮", question: "Quelle est la capitale de la Finlande ?", hint: "Au bord de la mer Baltique", answers: ["helsinki"] },
  { theme: "Géographie", emoji: "🇬🇷", question: "Quelle est la capitale de la Grèce ?", hint: "L'Acropole s'y trouve", answers: ["athenes", "athènes", "athens"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel est le plus grand lac d'Afrique ?", hint: "Son nom est aussi un prénom", answers: ["lac victoria", "victoria"] },

  // ===== CINÉMA =====
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film voit-on un lion nommé Simba ?", hint: "Film d'animation Disney 1994", answers: ["le roi lion", "the lion king", "roi lion"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue Iron Man dans les films Marvel ?", hint: "Robert Downey ...", answers: ["robert downey jr", "robert downey", "rdj"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quelle saga trouve-t-on Harry, Ron et Hermione ?", hint: "Magie et sorciers", answers: ["harry potter"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film Pixar met en scène un robot dans un monde dévasté ?", hint: "Son nom ressemble à un prénom", answers: ["wall-e", "walle", "wall e"] },
  { theme: "Cinéma", emoji: "🎬", question: "Qui réalise la saga 'Le Seigneur des Anneaux' ?", hint: "Réalisateur néo-zélandais", answers: ["peter jackson"] },
  { theme: "Cinéma", emoji: "🏆", question: "Quel film a remporté l'Oscar du meilleur film en 2020 ?", hint: "Film coréen de Bong Joon-ho", answers: ["parasite"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans 'Titanic', quel acteur joue Jack Dawson ?", hint: "Il a aussi joué dans Django", answers: ["leonardo dicaprio", "dicaprio", "leo dicaprio"] },
  { theme: "Cinéma", emoji: "🤖", question: "Quel personnage dit 'Je serai de retour' dans Terminator ?", hint: "Il deviendra gouverneur de Californie", answers: ["arnold schwarzenegger", "schwarzenegger", "terminator"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de Christopher Nolan parle de rêves dans des rêves ?", hint: "Avec Leonardo DiCaprio", answers: ["inception"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film trouve-t-on les personnages de Woody et Buzz ?", hint: "Pixar, jouets", answers: ["toy story"] },
  { theme: "Cinéma", emoji: "🦸", question: "Quel super-héros est aussi le prince du Wakanda ?", hint: "Longue vie au roi", answers: ["black panther", "la panthère noire"] },
  { theme: "Cinéma", emoji: "🎬", question: "Qui a réalisé 'Avatar' en 2009 ?", hint: "Il a aussi réalisé Titanic", answers: ["james cameron", "cameron"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film un comptable est-il faussement accusé de meurtre à Shawshank ?", hint: "Film de 1994", answers: ["les evades", "les évadés", "the shawshank redemption"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de 1999 parle d'un programme qui simule la réalité ?", hint: "Pilule rouge ou bleue ?", answers: ["matrix", "the matrix"] },
  { theme: "Cinéma", emoji: "🦁", question: "Dans quel film Meryl Streep joue-t-elle une chef de la mode redoutée ?", hint: "Anne Hathaway dans son ombre", answers: ["le diable s'habille en prada", "the devil wears prada"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de Quentin Tarantino se passe dans Los Angeles et parle d'un boxeur ?", hint: "Les histoires sont entrelacées", answers: ["pulp fiction"] },
  { theme: "Cinéma", emoji: "👻", question: "Dans quel film un enfant voit-il des morts ?", hint: "Bruce Willis, 1999", answers: ["sixieme sens", "sixième sens", "the sixth sense"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue le Joker dans 'The Dark Knight' ?", hint: "Il est décédé peu après", answers: ["heath ledger", "ledger"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film voit-on Forrest Gump courir aux USA ?", hint: "Tom Hanks, boîte de chocolats", answers: ["forrest gump"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film Disney raconte l'histoire d'une princesse avec de longs cheveux magiques ?", hint: "Raiponce en anglais", answers: ["raiponce", "tangled"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans 'Avengers: Endgame', qui dit 'Je suis Iron Man' ?", hint: "Robert Downey Jr", answers: ["tony stark", "iron man", "robert downey jr"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel réalisateur a fait 'Schindler's List' et 'Jurassic Park' ?", hint: "Steven ...", answers: ["steven spielberg", "spielberg"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel pays a été tourné la plupart des scènes du 'Seigneur des Anneaux' ?", hint: "Pays en forme de nuage", answers: ["nouvelle-zelande", "nouvelle zelande", "new zealand"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel personnage de Marvel crie 'Wakanda Forever' ?", hint: "Roi africain", answers: ["black panther", "tchalla", "t'challa"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de Pixar met en scène des monstres qui font peur aux enfants ?", hint: "Monstres et Cie", answers: ["monstres et cie", "monsters inc", "monsters inc."] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quelle ville se passe 'Midnight in Paris' de Woody Allen ?", hint: "Ville lumière", answers: ["paris"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue le rôle de James Bond le plus souvent ?", hint: "L'acteur ayant le plus joué Bond", answers: ["roger moore", "moore"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film d'animation raconte l'histoire d'un rat cuisinier à Paris ?", hint: "Pixar, 2007", answers: ["ratatouille"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel est le film le plus rentable de l'histoire du cinéma ?", hint: "Film de 2009, monde de Pandora", answers: ["avatar"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans 'La La Land', qui joue Mia ?", hint: "Emma ...", answers: ["emma stone", "stone"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de Ridley Scott se passe sur la planète Mars ?", hint: "Matt Damon survit seul", answers: ["seul sur mars", "the martian"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans 'Star Wars', qui est le père de Luke Skywalker ?", hint: "Je suis ton père", answers: ["dark vador", "darth vader", "anakin skywalker", "anakin"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de Nolan se déroule sur plusieurs plans temporels dans l'espace ?", hint: "Matthew McConaughey", answers: ["interstellar"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue Wolverine dans les X-Men ?", hint: "Acteur australien", answers: ["hugh jackman", "jackman"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film Tom Hanks est-il bloqué dans un aéroport ?", hint: "2004, Terminal", answers: ["le terminal", "the terminal"] },
  { theme: "Cinéma", emoji: "🎬", question: "Qui joue le rôle principal dans 'Joker' (2019) ?", hint: "Joaquin ...", answers: ["joaquin phoenix", "phoenix"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film d'horreur se passe dans un hôtel isolé avec Jack Nicholson ?", hint: "Stanley Kubrick, 'Redrum'", answers: ["shining", "the shining"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quelle actrice joue Hermione Granger ?", hint: "Emma ...", answers: ["emma watson", "watson"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film Audrey Hepburn mange-t-elle un croissant devant Tiffany's ?", hint: "New York, 1961", answers: ["diamants sur canape", "breakfast at tiffany's"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de 2010 raconte la création de Facebook ?", hint: "David Fincher", answers: ["the social network", "social network"] },

  // ===== MUSIQUE =====
  { theme: "Musique", emoji: "🎵", question: "Qui a chanté 'Thriller' en 1982 ?", hint: "Le roi de la pop", answers: ["michael jackson", "jackson"] },
  { theme: "Musique", emoji: "🎸", question: "Quel groupe chante 'Bohemian Rhapsody' ?", hint: "Le chanteur s'appelait Freddie Mercury", answers: ["queen"] },
  { theme: "Musique", emoji: "🎤", question: "Comment s'appelle la chanteuse de 'Bad Guy' ?", hint: "Prénom et nom commencent par B.E.", answers: ["billie eilish", "eilish"] },
  { theme: "Musique", emoji: "🥁", question: "De quel pays viennent les Beatles ?", hint: "John, Paul, George et Ringo", answers: ["angleterre", "royaume-uni", "royaume uni", "uk", "grande-bretagne"] },
  { theme: "Musique", emoji: "🎤", question: "Comment s'appelle le rappeur américain né Aubrey Graham ?", hint: "Ancienne star de Degrassi", answers: ["drake"] },
  { theme: "Musique", emoji: "🎵", question: "Quel pays a remporté l'Eurovision 2021 ?", hint: "Groupe de rock", answers: ["italie", "italy"] },
  { theme: "Musique", emoji: "🎸", question: "Quel groupe rock chante 'Smells Like Teen Spirit' ?", hint: "Kurt Cobain en était le leader", answers: ["nirvana"] },
  { theme: "Musique", emoji: "🎵", question: "Qui a composé la Symphonie n°9 en étant sourd ?", hint: "Compositeur allemand", answers: ["beethoven", "ludwig van beethoven"] },
  { theme: "Musique", emoji: "🎤", question: "Quelle chanteuse est connue pour 'Shake It Off' et 'Blank Space' ?", hint: "Taylor ...", answers: ["taylor swift", "swift"] },
  { theme: "Musique", emoji: "🎵", question: "Quel rappeur a sorti l'album 'DAMN.' en 2017 ?", hint: "Kendrick ...", answers: ["kendrick lamar", "kendrick"] },
  { theme: "Musique", emoji: "🎸", question: "Quel groupe chante 'Hotel California' ?", hint: "Les aigles en anglais", answers: ["eagles", "the eagles"] },
  { theme: "Musique", emoji: "🎤", question: "Qui chante 'Rolling in the Deep' ?", hint: "Chanteuse britannique à la voix puissante", answers: ["adele", "adèle"] },
  { theme: "Musique", emoji: "🎵", question: "Quelle chanteuse pop est aussi connue sous le nom de 'Queen B' ?", hint: "Beyoncé ...", answers: ["beyonce", "beyoncé"] },
  { theme: "Musique", emoji: "🎸", question: "Qui est le chanteur des Rolling Stones ?", hint: "Mick ...", answers: ["mick jagger", "jagger"] },
  { theme: "Musique", emoji: "🎤", question: "Quel chanteur français a chanté 'La Vie en Rose' ?", hint: "La môme piaf", answers: ["edith piaf", "piaf"] },
  { theme: "Musique", emoji: "🎵", question: "Quel artiste a vendu le plus d'albums dans l'histoire ?", hint: "Il avait une voix de crooner", answers: ["michael jackson", "elvis presley", "jackson"] },
  { theme: "Musique", emoji: "🎸", question: "Dans quel groupe jouait Freddie Mercury ?", hint: "Groupe de rock britannique", answers: ["queen"] },
  { theme: "Musique", emoji: "🎵", question: "Quel compositeur a écrit les '4 Saisons' ?", hint: "Compositeur baroque italien", answers: ["vivaldi", "antonio vivaldi"] },
  { theme: "Musique", emoji: "🎤", question: "Qui chante 'Uptown Funk' avec Mark Ronson ?", hint: "Bruno ...", answers: ["bruno mars", "mars"] },
  { theme: "Musique", emoji: "🎸", question: "Quel groupe anglais a chanté 'Wonderwall' ?", hint: "Frères Gallagher", answers: ["oasis"] },
  { theme: "Musique", emoji: "🎵", question: "Quel rappeur français a sorti l'album 'PNL' ?", hint: "Deux frères, Versailles", answers: ["pnl"] },
  { theme: "Musique", emoji: "🎤", question: "Qui chante 'Shape of You' ?", hint: "Ed ...", answers: ["ed sheeran", "sheeran"] },
  { theme: "Musique", emoji: "🎸", question: "Quel chanteur américain est connu comme 'The Boss' ?", hint: "Bruce ...", answers: ["bruce springsteen", "springsteen"] },
  { theme: "Musique", emoji: "🎵", question: "Quel groupe français a sorti 'One More Time' en 2000 ?", hint: "Casques robots", answers: ["daft punk"] },
  { theme: "Musique", emoji: "🎤", question: "Qui chante 'Lose Yourself' dans le film 8 Mile ?", hint: "Le rappeur blanc de Detroit", answers: ["eminem", "slim shady"] },
  { theme: "Musique", emoji: "🎸", question: "Dans quel groupe jouait Kurt Cobain ?", hint: "Grunge des années 90", answers: ["nirvana"] },
  { theme: "Musique", emoji: "🎵", question: "Quelle chanteuse a sorti 'Born This Way' ?", hint: "Lady ...", answers: ["lady gaga", "gaga"] },
  { theme: "Musique", emoji: "🎤", question: "Qui chante 'Bonjour' en 2021, album Civilisation ?", hint: "Oxmo Puccino et lui...", answers: ["orelsan", "aurelien cotentin"] },
  { theme: "Musique", emoji: "🎸", question: "Quel est le vrai nom de Stromae ?", hint: "Chanteur belge", answers: ["paul van haver"] },
  { theme: "Musique", emoji: "🎵", question: "Quelle chanteuse a interprété 'Chandelier' ?", hint: "Sia ...", answers: ["sia"] },

  // ===== SCIENCE =====
  { theme: "Science", emoji: "⚗️", question: "Quel est le symbole chimique de l'or ?", hint: "Deux lettres, commence par A", answers: ["au"] },
  { theme: "Science", emoji: "🔭", question: "Quelle est la planète la plus proche du Soleil ?", hint: "La plus petite du système solaire", answers: ["mercure", "mercury"] },
  { theme: "Science", emoji: "⚛️", question: "Quel scientifique a découvert la pénicilline ?", hint: "Alexander ...", answers: ["alexander fleming", "fleming"] },
  { theme: "Science", emoji: "🧬", question: "Quelle est la formule chimique de l'eau ?", hint: "2 hydrogènes, 1 oxygène", answers: ["h2o"] },
  { theme: "Science", emoji: "⚡", question: "Qui a inventé l'ampoule électrique ?", hint: "Thomas ...", answers: ["thomas edison", "edison"] },
  { theme: "Science", emoji: "🍎", question: "Quelle théorie est associée à la pomme qui tombe ?", hint: "Isaac Newton", answers: ["gravitation", "gravité", "loi de la gravitation", "attraction universelle"] },
  { theme: "Science", emoji: "🚀", question: "En quelle année Youri Gagarine est-il allé dans l'espace ?", hint: "Début des années 60", answers: ["1961"] },
  { theme: "Science", emoji: "⚗️", question: "Quel est le symbole chimique du fer ?", hint: "Deux lettres, latin", answers: ["fe"] },
  { theme: "Science", emoji: "🔭", question: "Combien de planètes dans notre système solaire ?", hint: "Depuis 2006, Pluton n'en est plus une", answers: ["8", "huit"] },
  { theme: "Science", emoji: "🧬", question: "Quelle est la molécule qui porte l'information génétique ?", hint: "Trois lettres", answers: ["adn", "dna"] },
  { theme: "Science", emoji: "⚛️", question: "Combien d'éléments dans le tableau périodique (approximativement) ?", hint: "Entre 115 et 120", answers: ["118", "cent dix-huit"] },
  { theme: "Science", emoji: "🌡️", question: "À quelle température l'eau bout-elle (en °C) ?", hint: "À pression normale", answers: ["100", "100 degres"] },
  { theme: "Science", emoji: "🧲", question: "Quel scientifique a développé la théorie de la relativité ?", hint: "Albert ...", answers: ["albert einstein", "einstein"] },
  { theme: "Science", emoji: "🔬", question: "Quelle scientifique a deux fois remporté le Prix Nobel ?", hint: "Marie ...", answers: ["marie curie", "curie"] },
  { theme: "Science", emoji: "🌍", question: "Combien de temps met la lumière pour aller du Soleil à la Terre ?", hint: "Environ 8 minutes", answers: ["8 minutes", "8", "environ 8 minutes"] },
  { theme: "Science", emoji: "⚡", question: "Quelle est la vitesse de la lumière en km/s (environ) ?", hint: "300 000 km/s", answers: ["300000", "300 000"] },
  { theme: "Science", emoji: "🧬", question: "Combien de chromosomes a un être humain (en paires) ?", hint: "23 paires", answers: ["46", "23 paires", "23"] },
  { theme: "Science", emoji: "🌡️", question: "Quel est le point de congélation de l'eau en Fahrenheit ?", hint: "32 degrés", answers: ["32", "32 fahrenheit"] },
  { theme: "Science", emoji: "🔭", question: "Quelle planète est la plus grande du système solaire ?", hint: "La géante gazeuse", answers: ["jupiter"] },
  { theme: "Science", emoji: "⚗️", question: "Quel gaz représente environ 78% de l'atmosphère terrestre ?", hint: "N₂", answers: ["azote", "nitrogen"] },
  { theme: "Science", emoji: "🧲", question: "Quel phénomène permet aux avions de voler ?", hint: "Liée à la pression de l'air", answers: ["portance", "poussee d'archimede"] },
  { theme: "Science", emoji: "🔬", question: "Combien d'os a le corps humain adulte ?", hint: "Environ 206", answers: ["206"] },
  { theme: "Science", emoji: "🧬", question: "Quelle vitamine produit le corps humain au soleil ?", hint: "Vitamine D", answers: ["vitamine d", "d"] },
  { theme: "Science", emoji: "🌡️", question: "Quelle est la température du noyau terrestre (en °C approx) ?", hint: "Autour de 5000 à 6000 °C", answers: ["5000", "6000", "5000 degres", "5500"] },
  { theme: "Science", emoji: "🔭", question: "Qu'est-ce qu'une année-lumière ?", hint: "Une distance, pas un temps", answers: ["distance", "distance parcourue par la lumiere en un an"] },
  { theme: "Science", emoji: "⚛️", question: "Qui a découvert la radioactivité ?", hint: "Henri ...", answers: ["henri becquerel", "becquerel"] },
  { theme: "Science", emoji: "🧬", question: "Quel organe produit l'insuline ?", hint: "Un organe digestif", answers: ["pancreas", "pancréas"] },
  { theme: "Science", emoji: "🌍", question: "À quelle vitesse la Terre tourne-t-elle autour du Soleil (km/h) ?", hint: "Environ 107 000 km/h", answers: ["107000", "107 000", "environ 107000"] },
  { theme: "Science", emoji: "🔬", question: "Quelle est la cellule la plus grande du corps humain ?", hint: "L'ovule", answers: ["ovule", "ovocyte"] },

  // ===== SPORT =====
  { theme: "Sport", emoji: "⚽", question: "Combien de joueurs sur le terrain dans une équipe de football ?", hint: "Gardien inclus", answers: ["11", "onze"] },
  { theme: "Sport", emoji: "🏀", question: "Quel joueur NBA est surnommé 'The Goat' ?", hint: "Il a joué pour les Bulls", answers: ["michael jordan", "jordan"] },
  { theme: "Sport", emoji: "🏊", question: "Quel nageur a remporté 23 médailles d'or olympiques ?", hint: "Michael ...", answers: ["michael phelps", "phelps"] },
  { theme: "Sport", emoji: "🥊", question: "Qui est surnommé 'The Greatest' dans la boxe ?", hint: "Muhammad ...", answers: ["muhammad ali", "ali", "cassius clay"] },
  { theme: "Sport", emoji: "⚽", question: "Quel pays a remporté le plus de Coupes du monde de football ?", hint: "Pays d'Amérique du Sud", answers: ["bresil", "brésil", "brazil"] },
  { theme: "Sport", emoji: "🎿", question: "Dans quelle ville ont eu lieu les JO d'été 2024 ?", hint: "Capitale européenne, Tour Eiffel", answers: ["paris"] },
  { theme: "Sport", emoji: "🏇", question: "Quel sport pratique-t-on à Wimbledon ?", hint: "Raquette et balle", answers: ["tennis"] },
  { theme: "Sport", emoji: "⚽", question: "Combien de buts Pelé a-t-il marqués en carrière (officiels) ?", hint: "Environ 760", answers: ["767", "760", "757"] },
  { theme: "Sport", emoji: "🏆", question: "Quelle équipe a remporté la Coupe du monde 2018 ?", hint: "Les Bleus", answers: ["france"] },
  { theme: "Sport", emoji: "🎾", question: "Combien de fois Rafael Nadal a-t-il remporté Roland-Garros ?", hint: "Le roi de la terre battue, 14 fois", answers: ["14", "quatorze"] },
  { theme: "Sport", emoji: "🏋️", question: "Quelle est la distance d'un marathon ?", hint: "42 km et quelque", answers: ["42,195 km", "42195", "42.195"] },
  { theme: "Sport", emoji: "⚽", question: "Dans quelle ville se trouve le stade de Wembley ?", hint: "Capitale de l'Angleterre", answers: ["londres", "london"] },
  { theme: "Sport", emoji: "🏀", question: "Combien de points vaut un panier à 3 points au basketball ?", hint: "La réponse est dans la question", answers: ["3", "trois"] },
  { theme: "Sport", emoji: "🎾", question: "Qui est la joueuse de tennis avec le plus de tournois du Grand Chelem ?", hint: "Serena ...", answers: ["serena williams", "williams"] },
  { theme: "Sport", emoji: "⚽", question: "Quel joueur a remporté le plus de Ballons d'Or ?", hint: "Argentin, 7 fois", answers: ["messi", "lionel messi"] },
  { theme: "Sport", emoji: "🏋️", question: "Dans quelle ville se déroulèrent les premiers Jeux Olympiques modernes ?", hint: "Grèce, 1896", answers: ["athenes", "athènes", "athens"] },
  { theme: "Sport", emoji: "🏒", question: "Combien de joueurs par équipe sur la glace en hockey ?", hint: "Gardien inclus", answers: ["6", "six"] },
  { theme: "Sport", emoji: "⚽", question: "Quel pays a organisé la Coupe du monde 2022 ?", hint: "Pays du Golfe", answers: ["qatar"] },
  { theme: "Sport", emoji: "🎾", question: "Qui est le recordman du nombre de semaines classé n°1 mondial en tennis (hommes) ?", hint: "Novak ...", answers: ["novak djokovic", "djokovic"] },
  { theme: "Sport", emoji: "🏋️", question: "Combien de buts Ronaldo (CR7) a-t-il marqués en équipe du Portugal ?", hint: "Plus de 100", answers: ["128", "130", "127"] },
  { theme: "Sport", emoji: "🏊", question: "Dans quel sport utilise-t-on un vélodrome ?", hint: "À vélo", answers: ["cyclisme", "velodrome"] },
  { theme: "Sport", emoji: "⚽", question: "Quelle est la compétition annuelle de clubs la plus importante en Europe ?", hint: "UEFA Champions League", answers: ["ligue des champions", "champions league", "ucl"] },
  { theme: "Sport", emoji: "🥊", question: "Dans quelle ville se trouve la salle mythique 'Madison Square Garden' ?", hint: "La Grande Pomme", answers: ["new york"] },
  { theme: "Sport", emoji: "🏋️", question: "Quel sport pratique Zinedine Zidane ?", hint: "Il a marqué un but de la tête en finale", answers: ["football", "foot"] },
  { theme: "Sport", emoji: "🏈", question: "Comment appelle-t-on la finale du championnat de football américain ?", hint: "Super ...", answers: ["super bowl"] },
  { theme: "Sport", emoji: "⛳", question: "Combien y a-t-il de trous dans un parcours de golf standard ?", hint: "18", answers: ["18", "dix-huit"] },
  { theme: "Sport", emoji: "🏊", question: "Quel est le style de natation le plus rapide ?", hint: "Le crawl", answers: ["crawl", "nage libre", "freestyle"] },
  { theme: "Sport", emoji: "⚽", question: "Combien de touches une équipe a-t-elle en volleyball avant d'envoyer le ballon ?", hint: "Maximum 3", answers: ["3", "trois"] },
  { theme: "Sport", emoji: "🎾", question: "Quel score s'appelle 'deuce' au tennis ?", hint: "40 à 40", answers: ["40 40", "egalite", "40-40"] },

  // ===== HISTOIRE =====
  { theme: "Histoire", emoji: "🏛️", question: "En quelle année a eu lieu la Révolution française ?", hint: "La Bastille a été prise cette année-là", answers: ["1789"] },
  { theme: "Histoire", emoji: "🏆", question: "En quelle année l'homme a-t-il marché sur la Lune ?", hint: "Mission Apollo 11", answers: ["1969"] },
  { theme: "Histoire", emoji: "✌️", question: "En quelle année s'est terminée la Seconde Guerre mondiale ?", hint: "Milieu des années 40", answers: ["1945"] },
  { theme: "Histoire", emoji: "🗽", question: "Quel pays a offert la Statue de la Liberté aux États-Unis ?", hint: "Pays de Napoléon", answers: ["france"] },
  { theme: "Histoire", emoji: "🧱", question: "En quelle année le mur de Berlin est-il tombé ?", hint: "Fin des années 80", answers: ["1989"] },
  { theme: "Histoire", emoji: "⚓", question: "Qui a découvert l'Amérique en 1492 ?", hint: "Christophe ...", answers: ["christophe colomb", "colomb", "christopher columbus", "columbus"] },
  { theme: "Histoire", emoji: "👑", question: "Qui était le roi de France lors de la Révolution française ?", hint: "Louis XVI", answers: ["louis xvi", "louis 16", "louis seize"] },
  { theme: "Histoire", emoji: "🏛️", question: "En quelle année Jules César a-t-il été assassiné ?", hint: "Avant notre ère, -44", answers: ["-44", "44 av jc", "44 avant jc"] },
  { theme: "Histoire", emoji: "⚔️", question: "Quelle bataille a marqué la défaite finale de Napoléon ?", hint: "En Belgique, 1815", answers: ["waterloo"] },
  { theme: "Histoire", emoji: "🏛️", question: "Qui a construit les pyramides de Gizeh ?", hint: "Civilisation nord-africaine antique", answers: ["egyptiens", "les egyptiens", "anciens egyptiens"] },
  { theme: "Histoire", emoji: "⚡", question: "En quelle année a eu lieu l'attentat contre les Twin Towers ?", hint: "11 septembre", answers: ["2001"] },
  { theme: "Histoire", emoji: "🚀", question: "En quelle année a été fondée la NASA ?", hint: "Fin des années 50", answers: ["1958"] },
  { theme: "Histoire", emoji: "🏛️", question: "Quelle empire a duré le plus longtemps dans l'histoire ?", hint: "Empire byzantin, plus de 1000 ans", answers: ["empire byzantin", "empire romain d'orient", "byzantin"] },
  { theme: "Histoire", emoji: "⚔️", question: "Quel pays a envahi la Pologne en septembre 1939 ?", hint: "Début de la WWII", answers: ["allemagne", "allemagne nazie", "allemagne hitlerienne"] },
  { theme: "Histoire", emoji: "🏛️", question: "Qui était le premier président des États-Unis ?", hint: "George ...", answers: ["george washington", "washington"] },
  { theme: "Histoire", emoji: "💣", question: "En quelle année a eu lieu le bombardement atomique d'Hiroshima ?", hint: "Fin de la WWII", answers: ["1945"] },
  { theme: "Histoire", emoji: "🏛️", question: "Quel pharaon est associé au masque funéraire en or le plus célèbre ?", hint: "Découvert en 1922", answers: ["toutankhamon", "toutankamon"] },
  { theme: "Histoire", emoji: "⚔️", question: "En quelle année a commencé la Première Guerre mondiale ?", hint: "L'attentat de Sarajevo", answers: ["1914"] },
  { theme: "Histoire", emoji: "🏛️", question: "Quel pays a utilisé la guillotine lors de sa Révolution ?", hint: "Pays des droits de l'homme", answers: ["france"] },
  { theme: "Histoire", emoji: "🚂", question: "En quelle année la Révolution industrielle a-t-elle débuté ?", hint: "18ème siècle, en Angleterre", answers: ["1760", "1750", "18eme siecle"] },
  { theme: "Histoire", emoji: "⚔️", question: "Quelle bataille en 732 arrêta l'expansion arabe en Europe occidentale ?", hint: "Charles Martel", answers: ["poitiers", "bataille de poitiers", "tours"] },
  { theme: "Histoire", emoji: "👑", question: "Combien de femmes Henry VIII a-t-il épousées ?", hint: "6 épouses", answers: ["6", "six"] },
  { theme: "Histoire", emoji: "🏛️", question: "En quelle année la France a-t-elle aboli l'esclavage définitivement ?", hint: "Sous la IIe République", answers: ["1848"] },
  { theme: "Histoire", emoji: "⚔️", question: "Quel empire a envahi Rome en 410 après JC ?", hint: "Wisigoths", answers: ["wisigoths", "les wisigoths"] },
  { theme: "Histoire", emoji: "🚀", question: "En quelle année Neil Armstrong a-t-il marché sur la Lune ?", hint: "Mission Apollo 11", answers: ["1969"] },
  { theme: "Histoire", emoji: "🏛️", question: "Quel général a conquis la Gaule ?", hint: "Jules ...", answers: ["jules cesar", "jules césar", "cesar", "caesar"] },
  { theme: "Histoire", emoji: "⚔️", question: "Quelle guerre opposa le Nord et le Sud des États-Unis ?", hint: "1861-1865", answers: ["guerre de secession", "guerre civile americaine", "civil war"] },
  { theme: "Histoire", emoji: "🧱", question: "En quelle année le mur de Berlin a-t-il été construit ?", hint: "1961", answers: ["1961"] },
  { theme: "Histoire", emoji: "🏛️", question: "Qui a été le premier homme à faire le tour du monde en bateau ?", hint: "Fernand ...", answers: ["magellan", "fernand magellan"] },

  // ===== CULTURE =====
  { theme: "Culture", emoji: "📚", question: "Qui a écrit 'Les Misérables' ?", hint: "Victor ...", answers: ["victor hugo", "hugo"] },
  { theme: "Culture", emoji: "🎨", question: "Qui a peint la Joconde ?", hint: "Génie de la Renaissance italienne", answers: ["leonard de vinci", "léonard de vinci", "da vinci", "leonardo da vinci"] },
  { theme: "Culture", emoji: "🏺", question: "De quelle matière est faite la Tour Eiffel ?", hint: "Métal rouillé à l'origine", answers: ["fer", "acier", "metal", "métal"] },
  { theme: "Culture", emoji: "🌐", question: "En quelle année a été créé Facebook ?", hint: "Mark Zuckerberg, Harvard", answers: ["2004"] },
  { theme: "Culture", emoji: "📱", question: "Quel pays a créé Samsung ?", hint: "Péninsule asiatique", answers: ["coree du sud", "corée du sud", "coree", "south korea"] },
  { theme: "Culture", emoji: "📚", question: "Qui a écrit '1984' ?", hint: "George ...", answers: ["george orwell", "orwell"] },
  { theme: "Culture", emoji: "🎨", question: "Qui a peint la Nuit Étoilée ?", hint: "Van ...", answers: ["van gogh", "vincent van gogh"] },
  { theme: "Culture", emoji: "📖", question: "Qui a écrit 'Le Petit Prince' ?", hint: "Antoine de ...", answers: ["antoine de saint-exupery", "saint-exupery", "saint exupery"] },
  { theme: "Culture", emoji: "🎨", question: "Qui a peint la Chapelle Sixtine ?", hint: "Michel-Ange", answers: ["michel-ange", "michel ange", "michelangelo"] },
  { theme: "Culture", emoji: "📚", question: "Qui a écrit 'Don Quichotte' ?", hint: "Miguel de ...", answers: ["cervantes", "miguel de cervantes"] },
  { theme: "Culture", emoji: "🎨", question: "Quelle est la peinture la plus chère jamais vendue ?", hint: "Salvator Mundi, de qui ?", answers: ["leonard de vinci", "da vinci"] },
  { theme: "Culture", emoji: "📖", question: "Qui a écrit 'Hamlet' ?", hint: "William ...", answers: ["shakespeare", "william shakespeare"] },
  { theme: "Culture", emoji: "🎨", question: "Dans quelle ville se trouve le musée du Louvre ?", hint: "Capitale française", answers: ["paris"] },
  { theme: "Culture", emoji: "📚", question: "Qui a écrit 'L'Étranger' ?", hint: "Albert ...", answers: ["albert camus", "camus"] },
  { theme: "Culture", emoji: "🎨", question: "Quel artiste espagnol est connu pour le cubisme ?", hint: "Pablo ...", answers: ["picasso", "pablo picasso"] },
  { theme: "Culture", emoji: "📖", question: "Dans quel roman Raskolnikov commet-il un meurtre ?", hint: "Dostoïevski", answers: ["crime et chatiment", "crime et châtiment"] },
  { theme: "Culture", emoji: "🎨", question: "Quel style artistique est associé à Salvador Dalí ?", hint: "Montres molles", answers: ["surrealisme", "surréalisme", "surrealism"] },
  { theme: "Culture", emoji: "📚", question: "Qui a écrit 'Madame Bovary' ?", hint: "Gustave ...", answers: ["flaubert", "gustave flaubert"] },
  { theme: "Culture", emoji: "📖", question: "Quel auteur a créé Sherlock Holmes ?", hint: "Arthur Conan ...", answers: ["arthur conan doyle", "conan doyle", "doyle"] },
  { theme: "Culture", emoji: "🎨", question: "Quel peintre impressionniste est connu pour ses nénuphars ?", hint: "Claude ...", answers: ["monet", "claude monet"] },
  { theme: "Culture", emoji: "📚", question: "Quel auteur a écrit 'Voyage au bout de la nuit' ?", hint: "Louis-Ferdinand ...", answers: ["celine", "céline", "louis-ferdinand celine"] },
  { theme: "Culture", emoji: "🏺", question: "Que signifie 'Renaissance' ?", hint: "Le mot littéralement", answers: ["renaitre", "renaître", "nouvelle naissance", "renouveau"] },
  { theme: "Culture", emoji: "📖", question: "Qui a écrit 'À la recherche du temps perdu' ?", hint: "Marcel ...", answers: ["proust", "marcel proust"] },
  { theme: "Culture", emoji: "🎨", question: "Quel peintre a coupé son oreille ?", hint: "Vincent van ...", answers: ["van gogh", "vincent van gogh"] },
  { theme: "Culture", emoji: "📚", question: "En quelle année a été publié 'Harry Potter à l'école des sorciers' ?", hint: "Années 90", answers: ["1997"] },
  { theme: "Culture", emoji: "📖", question: "Quel poète a écrit 'Les Fleurs du Mal' ?", hint: "Charles ...", answers: ["baudelaire", "charles baudelaire"] },
  { theme: "Culture", emoji: "🎨", question: "Dans quelle ville est né Pablo Picasso ?", hint: "Ville d'Espagne, région de Málaga", answers: ["malaga", "málaga"] },
  { theme: "Culture", emoji: "📚", question: "Qui a écrit 'Germinal' ?", hint: "Émile ...", answers: ["zola", "emile zola", "émile zola"] },
  { theme: "Culture", emoji: "📖", question: "Quel écrivain irlandais a écrit 'Ulysse' ?", hint: "James ...", answers: ["james joyce", "joyce"] },

  // ===== ANIMAUX =====
  { theme: "Animaux", emoji: "🐾", question: "Quel est l'animal le plus rapide du monde ?", hint: "Un félin des savanes africaines", answers: ["guépard", "gepard", "cheetah"] },
  { theme: "Animaux", emoji: "🐋", question: "Quel est le plus grand animal du monde ?", hint: "Un mammifère marin", answers: ["baleine bleue", "rorqual bleu", "blue whale"] },
  { theme: "Animaux", emoji: "🐘", question: "Combien de temps dure la gestation d'un éléphant (en mois) ?", hint: "Presque 2 ans", answers: ["22", "22 mois"] },
  { theme: "Animaux", emoji: "🦈", question: "Quel est le plus grand poisson du monde ?", hint: "Un requin inoffensif pour l'homme", answers: ["requin baleine", "whale shark"] },
  { theme: "Animaux", emoji: "🦁", question: "Comment appelle-t-on un groupe de lions ?", hint: "Comme une troupe de théâtre", answers: ["troupe", "troupe de lions", "pride"] },
  { theme: "Animaux", emoji: "🐧", question: "Sur quel continent vivent les pingouins naturellement ?", hint: "Pôle Sud", answers: ["antarctique", "antartique", "amerique du sud"] },
  { theme: "Animaux", emoji: "🦒", question: "Quel animal a le cou le plus long ?", hint: "Animal africain", answers: ["girafe"] },
  { theme: "Animaux", emoji: "🐊", question: "Quel reptile est le plus grand du monde ?", hint: "Crocodile ou alligator ?", answers: ["crocodile marin", "crocodile d'eau salee"] },
  { theme: "Animaux", emoji: "🦅", question: "Quel est le plus grand oiseau du monde (en envergure) ?", hint: "L'albatros ou condor", answers: ["albatros hurleur", "albatros"] },
  { theme: "Animaux", emoji: "🐢", question: "Combien d'années peut vivre une tortue des Galápagos ?", hint: "Plus de 100 ans", answers: ["150", "200", "100", "plus de 100 ans"] },
  { theme: "Animaux", emoji: "🦋", question: "Combien d'ailes a un papillon ?", hint: "Deux paires", answers: ["4", "quatre"] },
  { theme: "Animaux", emoji: "🐬", question: "Les dauphins sont-ils des poissons ou des mammifères ?", hint: "Ils respirent de l'air", answers: ["mammiferes", "mammifères"] },
  { theme: "Animaux", emoji: "🦓", question: "Quel animal a des rayures noires et blanches ?", hint: "Cousin du cheval en Afrique", answers: ["zebre", "zèbre"] },
  { theme: "Animaux", emoji: "🐙", question: "Combien de tentacules a une pieuvre ?", hint: "Huit", answers: ["8", "huit"] },
  { theme: "Animaux", emoji: "🦉", question: "Quel animal symbolise la sagesse ?", hint: "Oiseau nocturne", answers: ["hibou", "chouette"] },
  { theme: "Animaux", emoji: "🐝", question: "Comment appelle-t-on la femelle dominante dans une ruche ?", hint: "Reine", answers: ["reine", "reine des abeilles"] },
  { theme: "Animaux", emoji: "🦘", question: "Dans quel pays vivent les kangourous naturellement ?", hint: "Grande île-continent", answers: ["australie"] },
  { theme: "Animaux", emoji: "🐼", question: "De quoi se nourrit principalement le panda géant ?", hint: "Plante verte et creuse", answers: ["bambou"] },
  { theme: "Animaux", emoji: "🦩", question: "De quelle couleur est un flamant rose adulte ?", hint: "Couleur dans le nom", answers: ["rose", "rose et blanc"] },
  { theme: "Animaux", emoji: "🐠", question: "Quel poisson est le personnage principal de 'Le Monde de Nemo' ?", hint: "Poisson clown", answers: ["nemo", "poisson clown"] },
  { theme: "Animaux", emoji: "🦁", question: "Lequel du lion ou de la lionne chasse davantage ?", hint: "Pas le mâle", answers: ["lionne", "la lionne"] },
  { theme: "Animaux", emoji: "🐍", question: "Quel serpent est le plus venimeux du monde ?", hint: "Serpent taipan intérieur", answers: ["taipan", "taipan interieur"] },
  { theme: "Animaux", emoji: "🦌", question: "Comment appelle-t-on les bois d'un cerf ?", hint: "Ramifications sur la tête", answers: ["bois", "ramures"] },
  { theme: "Animaux", emoji: "🐳", question: "Combien de temps une baleine peut-elle apnée sous l'eau ?", hint: "Certaines jusqu'à 2 heures", answers: ["2 heures", "1 heure", "90 minutes"] },

  // ===== JEUX VIDÉO =====
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu incarne-t-on Link ?", hint: "Nintendo, épée et bouclier", answers: ["zelda", "the legend of zelda", "legend of zelda"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu se déroule dans la ville de Los Santos ?", hint: "GTA ...", answers: ["gta v", "gta 5", "grand theft auto v", "grand theft auto 5"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Comment s'appelle le plombier de Nintendo ?", hint: "Mario ...", answers: ["mario", "super mario"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu construit-on des maisons avec des blocs ?", hint: "Le jeu le plus vendu de l'histoire", answers: ["minecraft"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel personnage est le héros de la saga 'Sonic' ?", hint: "Il est bleu et très rapide", answers: ["sonic", "sonic the hedgehog"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu battle royale atterrit-on d'un bus volant ?", hint: "Fortnite", answers: ["fortnite"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel est le jeu de tir tactique le plus joué au monde sur PC ?", hint: "Counter-Strike", answers: ["counter-strike", "cs", "csgo", "cs2", "counter strike"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu joue-t-on à Geralt de Riv ?", hint: "Chasseur de monstres", answers: ["the witcher", "witcher"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quelle entreprise a créé PlayStation ?", hint: "Géant japonais de l'électronique", answers: ["sony"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu doit-on survivre à une île avec des zombies ?", hint: "Dayz, ou le premier battle royale", answers: ["pubg", "playerunknown's battlegrounds", "h1z1"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu de sport de Nintendo se joue avec des personnages stylisés ?", hint: "Jeu de kart", answers: ["mario kart"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu gère-t-on des villages de la préhistoire à nos jours ?", hint: "Age of ...", answers: ["age of empires"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel est le premier Pokémon de la Pokédex nationale ?", hint: "Numéro 1", answers: ["bulbizarre", "bulbasaur"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu joue-t-on à Master Chief ?", hint: "Halo", answers: ["halo"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu MOBA opposait deux équipes de 5 champions ?", hint: "League of ...", answers: ["league of legends", "lol"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel univers se passe le jeu 'Overwatch' ?", hint: "Futur proche, héros et super-pouvoirs", answers: ["futur", "overwatch"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel studio a créé God of War ?", hint: "Santa Monica Studio", answers: ["santa monica studio", "sony", "santa monica"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quelle ville se passe le jeu 'Cyberpunk 2077' ?", hint: "Night City", answers: ["night city"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu de survie se passe dans l'espace avec des imposteurs ?", hint: "Among ...", answers: ["among us"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu incarne-t-on Kratos ?", hint: "Dieu de la guerre", answers: ["god of war"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu de course de Nintendo permet de jouer en ligne à 12 joueurs ?", hint: "Mario Kart ...", answers: ["mario kart 8", "mario kart 8 deluxe", "mario kart"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu RPG incarne-t-on un Dragonborn en Tamriel ?", hint: "The Elder Scrolls...", answers: ["skyrim", "the elder scrolls v", "elder scrolls"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu de cartes numérique a été créé par Blizzard ?", hint: "Hearthstone", answers: ["hearthstone"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu doit-on collecter des étoiles dans les galaxies ?", hint: "Mario ...", answers: ["super mario galaxy"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel studio finlandais a créé Angry Birds ?", hint: "Rovio", answers: ["rovio"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu peut-on construire des fermes et élever des animaux en solo ou coop ?", hint: "Stardew Valley", answers: ["stardew valley"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel personnage de Zelda est l'antagoniste principal ?", hint: "Le mal suprême", answers: ["ganon", "ganondorf"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel jeu de battle royale d'Epic Games est free-to-play ?", hint: "Commence par F", answers: ["fortnite"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Dans quel jeu gère-t-on une ville et ses habitants ?", hint: "Cities: ...", answers: ["cities skylines", "simcity"] },
  { theme: "Jeux vidéo", emoji: "🎮", question: "Quel Pokémon légendaire représente la mer ?", hint: "Kyogre", answers: ["kyogre"] },

  // ===== SÉRIES TV =====
  { theme: "Séries", emoji: "📺", question: "Dans quelle série voit-on des dragons et un Trône de Fer ?", hint: "HBO, dragons et batailles", answers: ["game of thrones", "got"] },
  { theme: "Séries", emoji: "📺", question: "Comment s'appelle le personnage principal de 'Breaking Bad' ?", hint: "Professeur de chimie", answers: ["walter white", "heisenberg", "walter"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série Netflix met en scène des adolescents dans le Monde à l'Envers ?", hint: "Eleven et ses amis", answers: ["stranger things"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle ville se passe 'Emily in Paris' ?", hint: "Ville lumière", answers: ["paris"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série coréenne met en scène des jeux dangereux pour de l'argent ?", hint: "Le jeu du calmar", answers: ["squid game", "le jeu du calmar"] },
  { theme: "Séries", emoji: "📺", question: "Dans 'Friends', comment s'appelle le frère de Monica ?", hint: "Ross ...", answers: ["ross", "ross geller"] },
  { theme: "Séries", emoji: "📺", question: "Combien de saisons a 'Breaking Bad' ?", hint: "5 saisons", answers: ["5", "cinq"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série voit-on des zombies dans un monde post-apocalyptique ?", hint: "The Walking ...", answers: ["the walking dead", "walking dead"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série se passe dans l'univers de Westeros ?", hint: "Dragons et royaumes", answers: ["game of thrones", "got", "house of the dragon"] },
  { theme: "Séries", emoji: "📺", question: "Dans 'La Casa de Papel', quel est le surnom du chef des braqueurs ?", hint: "Une ville", answers: ["le professeur", "professor", "sergio"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série Amazon se passe dans un univers de super-héros corrompus ?", hint: "The Boys", answers: ["the boys"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série joue Bryan Cranston avant Breaking Bad ?", hint: "Famille dysfonctionnelle, comédie", answers: ["malcolm", "malcolm in the middle"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série HBO suit des femmes en Nouvelle-Angleterre dans une dystopie religieuse ?", hint: "The Handmaid's Tale", answers: ["the handmaid's tale", "la servante ecarlate"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série voit-on Don Draper comme publicitaire dans les années 60 ?", hint: "Mad Men", answers: ["mad men"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série Netflix suit un lycéen qui trouve un carnet de mort ?", hint: "Adaptation d'un manga", answers: ["death note"] },
  { theme: "Séries", emoji: "📺", question: "Dans 'How I Met Your Mother', par quel personnage commence l'histoire ?", hint: "Ted ...", answers: ["ted", "ted mosby"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série se déroule dans l'Angleterre victorienne avec un détective génial ?", hint: "BBC, Cumberbatch", answers: ["sherlock"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série joue Jeffrey Dean Morgan en méchant avec une batte ?", hint: "Negan dans...", answers: ["the walking dead", "walking dead"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série suit un avocat qui ne peut pas mentir ?", hint: "Suits, ou un autre", answers: ["liar liar", "suits"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série Netflix voit-on des ados jouer à des jeux d'argent style anime ?", hint: "Kakegurui", answers: ["kakegurui"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série HBO parle de deux détectives enquêtant sur un meurtre rituel en Louisiane ?", hint: "True ...", answers: ["true detective"] },
  { theme: "Séries", emoji: "📺", question: "Dans 'Narcos', quel célèbre trafiquant est au cœur de l'intrigue ?", hint: "Pablo ...", answers: ["pablo escobar", "escobar"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série turque est l'une des plus vues sur Netflix en Europe ?", hint: "Resurrectio ou une autre", answers: ["dirilis ertugrul", "le siecle magnifique"] },
  { theme: "Séries", emoji: "📺", question: "Dans quelle série joue Emilia Clarke en reine des dragons ?", hint: "Game of Thrones", answers: ["game of thrones"] },
  { theme: "Séries", emoji: "📺", question: "Quelle série se déroule dans un lycée espagnol et parle d'argent et de drame ?", hint: "Elite", answers: ["elite"] },

  // ===== GASTRONOMIE =====
  { theme: "Gastronomie", emoji: "🍕", question: "De quel pays vient la pizza ?", hint: "Botte méditerranéenne", answers: ["italie", "italy"] },
  { theme: "Gastronomie", emoji: "🥐", question: "Quel est le petit-déjeuner français emblématique ?", hint: "Pâtisserie en forme de croissant", answers: ["croissant"] },
  { theme: "Gastronomie", emoji: "🍣", question: "De quel pays vient le sushi ?", hint: "Pays du Soleil Levant", answers: ["japon", "japan"] },
  { theme: "Gastronomie", emoji: "🥘", question: "Qu'est-ce que la paella ?", hint: "Plat espagnol à base de...", answers: ["riz", "riz espagnol", "plat de riz"] },
  { theme: "Gastronomie", emoji: "🍫", question: "Quel pays est le plus grand producteur de cacao au monde ?", hint: "Côte d'...", answers: ["cote d'ivoire", "cote divoire", "ivory coast"] },
  { theme: "Gastronomie", emoji: "🥗", question: "Dans quelle ville française vit la cuisine gastronomique au plus haut niveau ?", hint: "Capitale mondiale de la gastronomie", answers: ["lyon", "paris"] },
  { theme: "Gastronomie", emoji: "🍷", question: "Quelle région française est réputée pour ses vins rouges de Bordeaux ?", hint: "Au bord de la Gironde", answers: ["bordeaux", "gironde"] },
  { theme: "Gastronomie", emoji: "🧀", question: "Quel pays produit le plus de fromages différents ?", hint: "Plus de 1000 variétés", answers: ["france"] },
  { theme: "Gastronomie", emoji: "🍜", question: "De quel pays vient le ramen ?", hint: "Influencé par la Chine", answers: ["japon"] },
  { theme: "Gastronomie", emoji: "🥩", question: "Dans quel pays mange-t-on le 'boeuf Wellington' ?", hint: "Pays d'origine anglaise", answers: ["angleterre", "royaume-uni", "uk"] },
  { theme: "Gastronomie", emoji: "🍺", question: "Quelle bière allemande est la plus célèbre ?", hint: "Blonde du nord", answers: ["becks", "paulaner", "weizen", "hefeweizen"] },
  { theme: "Gastronomie", emoji: "🥐", question: "Quelle pâtisserie française est composée de pâte à choux fourrée de crème ?", hint: "En forme de doigt allongé", answers: ["eclair", "éclair"] },
  { theme: "Gastronomie", emoji: "🍕", question: "Quels sont les ingrédients de la pizza margherita ?", hint: "Tomate, mozzarella et ...", answers: ["basilic", "tomate mozzarella basilic"] },
  { theme: "Gastronomie", emoji: "🌮", question: "De quel pays vient le taco ?", hint: "Amérique centrale", answers: ["mexique", "mexico"] },
  { theme: "Gastronomie", emoji: "🍣", question: "Comment appelle-t-on le plat japonais de poisson cru ?", hint: "Sashimi ou ...", answers: ["sashimi", "sushi"] },
  { theme: "Gastronomie", emoji: "🥗", question: "Quelle salade est faite de laitue romaine, croûtons et parmesan ?", hint: "César ...", answers: ["salade cesar", "salade césar", "caesar salad"] },
  { theme: "Gastronomie", emoji: "🍫", question: "De quel pays vient le chocolat suisse ?", hint: "Dans son nom", answers: ["suisse"] },
  { theme: "Gastronomie", emoji: "🍺", question: "De quel pays vient la Guinness ?", hint: "Île verte", answers: ["irlande", "ireland"] },
  { theme: "Gastronomie", emoji: "🥘", question: "Quel est le plat national de l'Espagne ?", hint: "Riz aux fruits de mer", answers: ["paella"] },
  { theme: "Gastronomie", emoji: "🍷", question: "Dans quelle région de France produit-on le Champagne ?", hint: "Région au nord-est", answers: ["champagne", "champagne-ardenne"] },

  // ===== TECHNOLOGIE =====
  { theme: "Technologie", emoji: "💻", question: "Qui a fondé Apple avec Steve Jobs ?", hint: "Steve ...", answers: ["steve wozniak", "wozniak"] },
  { theme: "Technologie", emoji: "📱", question: "En quelle année le premier iPhone est-il sorti ?", hint: "Steve Jobs l'a annoncé", answers: ["2007"] },
  { theme: "Technologie", emoji: "🌐", question: "Qui a inventé le World Wide Web ?", hint: "Tim Berners-...", answers: ["tim berners-lee", "berners-lee"] },
  { theme: "Technologie", emoji: "💻", question: "Quel est le système d'exploitation le plus utilisé sur les serveurs ?", hint: "Pingouin", answers: ["linux"] },
  { theme: "Technologie", emoji: "🔍", question: "En quelle année Google a-t-il été fondé ?", hint: "Fin des années 90", answers: ["1998"] },
  { theme: "Technologie", emoji: "📱", question: "Quel réseau social a été lancé en 2010 par Kevin Systrom ?", hint: "Photos et filtres", answers: ["instagram"] },
  { theme: "Technologie", emoji: "💻", question: "Que signifie CPU ?", hint: "Central Processing ...", answers: ["central processing unit", "processeur central"] },
  { theme: "Technologie", emoji: "🤖", question: "Quelle entreprise a créé ChatGPT ?", hint: "OpenAI", answers: ["openai", "open ai"] },
  { theme: "Technologie", emoji: "🌐", question: "Que signifie HTTP ?", hint: "HyperText Transfer ...", answers: ["hypertext transfer protocol"] },
  { theme: "Technologie", emoji: "💻", question: "Quel langage de programmation a été créé par Guido van Rossum ?", hint: "Serpent", answers: ["python"] },
  { theme: "Technologie", emoji: "📱", question: "Quel réseau social est connu pour ses vidéos courtes ?", hint: "TikTok", answers: ["tiktok", "tik tok"] },
  { theme: "Technologie", emoji: "🔍", question: "Quel moteur de recherche est le plus utilisé dans le monde ?", hint: "Google", answers: ["google"] },
  { theme: "Technologie", emoji: "💻", question: "Qui est le fondateur de Microsoft ?", hint: "Bill ...", answers: ["bill gates", "gates"] },
  { theme: "Technologie", emoji: "🚀", question: "Quelle entreprise a lancé la fusée Falcon 9 ?", hint: "SpaceX", answers: ["spacex"] },
  { theme: "Technologie", emoji: "📱", question: "Que signifie Wi-Fi ?", hint: "Wireless Fidelity en anglais", answers: ["wireless fidelity"] },
  { theme: "Technologie", emoji: "💻", question: "Quel format de fichier est utilisé pour les images sans perte ?", hint: "PNG ou ...", answers: ["png", "tiff", "bmp"] },
  { theme: "Technologie", emoji: "🤖", question: "Quel géant tech a développé l'assistant vocal Alexa ?", hint: "E-commerce géant", answers: ["amazon"] },
  { theme: "Technologie", emoji: "🌐", question: "Combien de bits dans un octet ?", hint: "Nombre magique", answers: ["8", "huit"] },
  { theme: "Technologie", emoji: "💻", question: "Que signifie RAM ?", hint: "Mémoire vive", answers: ["random access memory"] },
  { theme: "Technologie", emoji: "📱", question: "Quel est l'OS mobile le plus répandu dans le monde ?", hint: "De Google", answers: ["android"] },

  // ===== GÉOGRAPHIE AVANCÉE =====
  { theme: "Géographie", emoji: "🌍", question: "Quel pays possède le plus grand nombre d'îles au monde ?", hint: "Pays scandinave", answers: ["suede", "suède", "sweden"] },
  { theme: "Géographie", emoji: "🏔️", question: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", hint: "Oural", answers: ["oural", "monts oural"] },
  { theme: "Géographie", emoji: "🌊", question: "Quelle mer se trouve entre la Grèce et la Turquie ?", hint: "Mer Égée", answers: ["mer egee", "mer égée", "egee"] },
  { theme: "Géographie", emoji: "🌍", question: "Quel pays est le plus grand en Afrique ?", hint: "Pas le Sahara lui-même", answers: ["algerie", "algérie"] },
  { theme: "Géographie", emoji: "🏙️", question: "Dans quelle ville se trouve le Colisée ?", hint: "La ville éternelle", answers: ["rome"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel fleuve traverse Paris ?", hint: "La ...", answers: ["seine", "la seine"] },
  { theme: "Géographie", emoji: "🏔️", question: "Quel pays est surnommé le 'Pays du Soleil Levant' ?", hint: "Asie de l'Est", answers: ["japon"] },
  { theme: "Géographie", emoji: "🌍", question: "Quelle mer borde Israël à l'ouest ?", hint: "Mer interne de l'Europe", answers: ["mediterranee", "méditerranée", "mer mediterranee"] },
  { theme: "Géographie", emoji: "🏙️", question: "Dans quelle ville se trouve le parlement européen ?", hint: "Ville alsacienne", answers: ["strasbourg"] },
  { theme: "Géographie", emoji: "🌊", question: "Quel est le plus grand lac d'Europe ?", hint: "En Finlande ou en Russie", answers: ["lac ladoga", "ladoga"] },

  // ===== POLITIQUE =====
  { theme: "Politique", emoji: "🏛️", question: "Quel est le nom du parlement français ?", hint: "Assemblée nationale et ...", answers: ["parlement", "assemblee nationale", "senat"] },
  { theme: "Politique", emoji: "🇺🇸", question: "Combien de sièges au Sénat américain ?", hint: "Deux par État, 50 États", answers: ["100", "cent"] },
  { theme: "Politique", emoji: "🌍", question: "Quel est le siège de l'ONU ?", hint: "Grande ville américaine", answers: ["new york"] },
  { theme: "Politique", emoji: "🏛️", question: "Quelle est la devise de la France ?", hint: "Trois mots", answers: ["liberte egalite fraternite", "liberté égalité fraternité"] },
  { theme: "Politique", emoji: "🇪🇺", question: "Combien d'étoiles sur le drapeau européen ?", hint: "Nombre fixe", answers: ["12", "douze"] },
  { theme: "Politique", emoji: "🏛️", question: "Qui élit le président de la République française ?", hint: "Suffrage universel direct", answers: ["les citoyens francais", "le peuple", "les francais"] },
  { theme: "Politique", emoji: "🇺🇸", question: "Combien d'États composent les États-Unis ?", hint: "Le nombre d'étoiles sur le drapeau", answers: ["50", "cinquante"] },
  { theme: "Politique", emoji: "🏛️", question: "Quelle est la durée du mandat présidentiel en France ?", hint: "Depuis 2000", answers: ["5 ans", "cinq ans"] },

  // ===== ASTRONOMIE =====
  { theme: "Astronomie", emoji: "🌌", question: "Comment s'appelle notre galaxie ?", hint: "Voie ...", answers: ["voie lactee", "voie lactée", "milky way"] },
  { theme: "Astronomie", emoji: "🌑", question: "Quel astre cause les éclipses solaires ?", hint: "Il tourne autour de la Terre", answers: ["lune"] },
  { theme: "Astronomie", emoji: "🔭", question: "Quel télescope spatial a succédé au Hubble ?", hint: "James Webb ...", answers: ["james webb", "jwst"] },
  { theme: "Astronomie", emoji: "🌠", question: "Comment s'appelle l'étoile la plus proche du Soleil ?", hint: "Proxima ...", answers: ["proxima centauri", "proxima du centaure"] },
  { theme: "Astronomie", emoji: "🪐", question: "Quelle planète a des anneaux visibles depuis la Terre ?", hint: "6ème du système solaire", answers: ["saturne", "saturn"] },
  { theme: "Astronomie", emoji: "☄️", question: "Qu'est-ce qu'une comète ?", hint: "Noyau de glace et de poussière", answers: ["astre", "corps celeste", "noyau de glace"] },
  { theme: "Astronomie", emoji: "🌌", question: "Quel trou noir a été photographié pour la première fois en 2019 ?", hint: "Au centre de M87", answers: ["m87", "powehi"] },
  { theme: "Astronomie", emoji: "🚀", question: "Quelle est la station spatiale internationale habitée ?", hint: "ISS", answers: ["iss", "station spatiale internationale"] },
  { theme: "Astronomie", emoji: "🌍", question: "Combien de lunes a Mars ?", hint: "Deux petites lunes", answers: ["2", "deux"] },
  { theme: "Astronomie", emoji: "🔭", question: "Quel est le nom du premier satellite artificiel ?", hint: "Lancé par l'URSS en 1957", answers: ["spoutnik", "sputnik"] },

  // ===== LANGUES =====
  { theme: "Langues", emoji: "🗣️", question: "Quelle est la langue la plus parlée dans le monde ?", hint: "En Chine", answers: ["mandarin", "chinois mandarin", "chinois"] },
  { theme: "Langues", emoji: "🗣️", question: "Combien de langues officielles y a-t-il en Suisse ?", hint: "4 langues", answers: ["4", "quatre"] },
  { theme: "Langues", emoji: "🗣️", question: "Quelle langue est parlée au Brésil ?", hint: "Pas l'espagnol", answers: ["portugais"] },
  { theme: "Langues", emoji: "🗣️", question: "Que signifie 'Merci' en japonais ?", hint: "Arigatou", answers: ["arigatou", "arigatou gozaimasu", "merci"] },
  { theme: "Langues", emoji: "🗣️", question: "Dans quelle langue est écrit 'War and Peace' ?", hint: "Tolstoï", answers: ["russe", "russian"] },
  { theme: "Langues", emoji: "🗣️", question: "Quelle est la langue officielle de l'Égypte ?", hint: "Langue sémitique", answers: ["arabe"] },
  { theme: "Langues", emoji: "🗣️", question: "Combien de lettres dans l'alphabet arabe ?", hint: "28", answers: ["28", "vingt-huit"] },

  // ===== MATHÉMATIQUES =====
  { theme: "Maths", emoji: "➗", question: "Combien font 15 x 15 ?", hint: "225", answers: ["225"] },
  { theme: "Maths", emoji: "➕", question: "Quel est le nombre pi (2 décimales) ?", hint: "3,14", answers: ["3.14", "3,14"] },
  { theme: "Maths", emoji: "➗", question: "Qu'est-ce qu'un nombre premier ?", hint: "Divisible uniquement par 1 et lui-même", answers: ["divisible par 1 et lui meme", "nombre divisible par 1 et lui-meme"] },
  { theme: "Maths", emoji: "➕", question: "Combien font 12² ?", hint: "144", answers: ["144"] },
  { theme: "Maths", emoji: "➗", question: "Combien de côtés a un hexagone ?", hint: "Hex = 6", answers: ["6", "six"] },
  { theme: "Maths", emoji: "➕", question: "Combien font 7 x 8 ?", hint: "56", answers: ["56"] },
  { theme: "Maths", emoji: "➗", question: "Quelle est la racine carrée de 144 ?", hint: "12", answers: ["12"] },
  { theme: "Maths", emoji: "➕", question: "Combien de degrés dans un triangle ?", hint: "180 au total", answers: ["180", "180 degres"] },
  { theme: "Maths", emoji: "➗", question: "Comment appelle-t-on un triangle avec trois côtés égaux ?", hint: "Équilatéral", answers: ["equilateral", "equilatéral", "triangle equilatéral"] },
  { theme: "Maths", emoji: "➕", question: "Combien font 2 puissance 10 ?", hint: "1024", answers: ["1024"] },

  // ===== MÉTÉO & NATURE =====
  { theme: "Nature", emoji: "🌦️", question: "Comment appelle-t-on un vent très chaud qui souffle du Sahara vers l'Europe ?", hint: "Le Sirocco", answers: ["sirocco"] },
  { theme: "Nature", emoji: "🌪️", question: "Comment appelle-t-on une tornade qui se forme sur l'eau ?", hint: "Trombe marine", answers: ["trombe", "trombe marine", "waterspout"] },
  { theme: "Nature", emoji: "🌈", question: "Combien de couleurs dans un arc-en-ciel ?", hint: "7 couleurs", answers: ["7", "sept"] },
  { theme: "Nature", emoji: "🌊", question: "Comment appelle-t-on un tsunami au Japon ?", hint: "C'est le terme japonais original", answers: ["tsunami"] },
  { theme: "Nature", emoji: "🌡️", question: "Quel est le phénomène qui réchauffe la Terre ?", hint: "Effet de ...", answers: ["effet de serre", "serre"] },
  { theme: "Nature", emoji: "🌿", question: "Quelle est la plante qui pousse le plus vite ?", hint: "Bambou", answers: ["bambou"] },
  { theme: "Nature", emoji: "🌊", question: "Combien de pourcentage d'eau couvre la Terre ?", hint: "Environ 70%", answers: ["71", "70", "70%", "71%"] },
  { theme: "Nature", emoji: "❄️", question: "Quelle est la couche protectrice de la Terre contre les UV ?", hint: "Couche d'ozone", answers: ["ozone", "couche d'ozone"] },
  { theme: "Nature", emoji: "🌋", question: "Comment appelle-t-on la roche liquide dans un volcan ?", hint: "Lave ou ...", answers: ["magma", "lave"] },
  { theme: "Nature", emoji: "🌦️", question: "Que mesure un baromètre ?", hint: "La pression", answers: ["pression atmospherique", "pression", "pression de l'air"] },

  // ===== MYTHOLOGIE =====
  { theme: "Mythologie", emoji: "⚡", question: "Qui est le roi des dieux grecs ?", hint: "Zeus", answers: ["zeus"] },
  { theme: "Mythologie", emoji: "🌊", question: "Qui est le dieu de la mer dans la mythologie grecque ?", hint: "Poséidon", answers: ["poseidon", "poséidon"] },
  { theme: "Mythologie", emoji: "☀️", question: "Qui est le dieu du soleil en mythologie grecque ?", hint: "Apollo ou Helios", answers: ["apollo", "apollon", "helios"] },
  { theme: "Mythologie", emoji: "🔨", question: "Qui est le dieu romain équivalent à Zeus ?", hint: "Jupiter", answers: ["jupiter"] },
  { theme: "Mythologie", emoji: "❤️", question: "Qui est la déesse de l'amour en mythologie grecque ?", hint: "Aphrodite", answers: ["aphrodite"] },
  { theme: "Mythologie", emoji: "🏹", question: "Qui est le dieu de la guerre en mythologie grecque ?", hint: "Arès", answers: ["ares", "arès", "mars"] },
  { theme: "Mythologie", emoji: "⚡", question: "Quel héros grec a combattu le Minotaure ?", hint: "Thésée", answers: ["thesee", "thésée", "theseus"] },
  { theme: "Mythologie", emoji: "🌊", question: "Quel monstre marin de la mythologie avale les navires ?", hint: "Charybde", answers: ["charybde", "scylla"] },
  { theme: "Mythologie", emoji: "🏔️", question: "Quel géant est condamné à porter le monde sur ses épaules ?", hint: "Atlas", answers: ["atlas"] },
  { theme: "Mythologie", emoji: "🦅", question: "Quel héros porte des sandales ailées dans la mythologie grecque ?", hint: "Hermès ou Persée", answers: ["hermes", "hermès", "persee", "persée"] },

  // ===== RELIGION =====
  { theme: "Religion", emoji: "✝️", question: "Quel est le livre sacré des chrétiens ?", hint: "La Bible", answers: ["bible", "la bible"] },
  { theme: "Religion", emoji: "☪️", question: "Quel est le livre sacré des musulmans ?", hint: "Le Coran", answers: ["coran", "le coran"] },
  { theme: "Religion", emoji: "✡️", question: "Quel est le livre sacré des juifs ?", hint: "La Torah", answers: ["torah", "la torah"] },
  { theme: "Religion", emoji: "☸️", question: "Qui a fondé le bouddhisme ?", hint: "Siddhartha ...", answers: ["bouddha", "siddhartha gautama", "gautama"] },
  { theme: "Religion", emoji: "🕌", question: "Quelle ville est la plus sacrée de l'Islam ?", hint: "En Arabie Saoudite", answers: ["la mecque", "mecque", "mecca"] },
  { theme: "Religion", emoji: "✝️", question: "Dans quelle ville Jésus a-t-il été crucifié ?", hint: "En Israël", answers: ["jerusalem", "jérusalem"] },
  { theme: "Religion", emoji: "🕍", question: "Quel est le lieu de prière des juifs ?", hint: "Synagogue", answers: ["synagogue"] },
  { theme: "Religion", emoji: "🕌", question: "Quel est le lieu de prière des musulmans ?", hint: "Mosquée", answers: ["mosquee", "mosquée"] },

  // ===== LITTÉRATURE =====
  { theme: "Littérature", emoji: "📖", question: "Qui a écrit 'L'Odyssée' ?", hint: "Poète grec antique", answers: ["homere", "homère", "homer"] },
  { theme: "Littérature", emoji: "📚", question: "Quel est le roman le plus vendu de tous les temps ?", hint: "Livre religieux ou littéraire...", answers: ["don quichotte", "le petit prince", "harry potter"] },
  { theme: "Littérature", emoji: "📖", question: "Qui a écrit 'Crime et Châtiment' ?", hint: "Auteur russe", answers: ["dostoievski", "dostoïevski", "fyodor dostoievski"] },
  { theme: "Littérature", emoji: "📚", question: "Dans quel roman Jonathan Swift parle-t-il de lilliputiens ?", hint: "Les voyages de ...", answers: ["les voyages de gulliver", "gulliver", "gulliver's travels"] },
  { theme: "Littérature", emoji: "📖", question: "Qui a écrit 'Le Comte de Monte-Cristo' ?", hint: "Alexandre ...", answers: ["alexandre dumas", "dumas"] },
  { theme: "Littérature", emoji: "📚", question: "Quel livre de Tolkien précède 'Le Seigneur des Anneaux' ?", hint: "Le Hobbit", answers: ["le hobbit", "the hobbit", "hobbit"] },

  // ===== ÉCONOMIE =====
  { theme: "Économie", emoji: "💰", question: "Quelle est la monnaie du Japon ?", hint: "Le Yen", answers: ["yen"] },
  { theme: "Économie", emoji: "💱", question: "Quelle est la monnaie des États-Unis ?", hint: "Dollar", answers: ["dollar", "dollar americain"] },
  { theme: "Économie", emoji: "💰", question: "Quelle est la monnaie de la Grande-Bretagne ?", hint: "Livre ...", answers: ["livre sterling", "pound", "sterling"] },
  { theme: "Économie", emoji: "🏦", question: "Dans quelle ville se trouve la Bourse de New York (NYSE) ?", hint: "Wall Street", answers: ["new york"] },
  { theme: "Économie", emoji: "💰", question: "Quelle est l'entreprise la plus valorisée au monde (2024) ?", hint: "Nvidia ou Apple", answers: ["nvidia", "apple", "microsoft"] },
  { theme: "Économie", emoji: "📈", question: "Que signifie PIB ?", hint: "Produit Intérieur ...", answers: ["produit interieur brut", "produit intérieur brut"] },

  // ===== ARTS ET SPECTACLE =====
  { theme: "Arts", emoji: "🎭", question: "Dans quelle ville se trouve Broadway ?", hint: "Grande Pomme", answers: ["new york"] },
  { theme: "Arts", emoji: "🎨", question: "Quelle est la danse nationale de l'Argentine ?", hint: "Danse de passion", answers: ["tango"] },
  { theme: "Arts", emoji: "🎭", question: "Qui a écrit 'Roméo et Juliette' ?", hint: "William ...", answers: ["shakespeare", "william shakespeare"] },
  { theme: "Arts", emoji: "🎪", question: "Dans quelle ville est né le cirque moderne ?", hint: "Angleterre, 18ème siècle", answers: ["londres", "london", "angleterre"] },
  { theme: "Arts", emoji: "🎨", question: "Quel mouvement artistique est caractérisé par des tableaux de points colorés ?", hint: "Pointillisme", answers: ["pointillisme"] },
  { theme: "Arts", emoji: "🎭", question: "Qui est le personnage central de 'Faust' ?", hint: "Goethe", answers: ["faust"] },

  // ===== MÉDECINE =====
  { theme: "Médecine", emoji: "🏥", question: "Quel est l'organe qui pompe le sang ?", hint: "Dans la poitrine", answers: ["coeur", "cœur"] },
  { theme: "Médecine", emoji: "💊", question: "Quel médicament courant réduit la fièvre ?", hint: "Paracétamol ou ...", answers: ["paracetamol", "paracétamol", "aspirine", "doliprane"] },
  { theme: "Médecine", emoji: "🩺", question: "Quel est le groupe sanguin universel donneur ?", hint: "O négatif", answers: ["o negatif", "o-", "o negatif"] },
  { theme: "Médecine", emoji: "🏥", question: "Combien de dents a un adulte humain (dents de sagesse incluses) ?", hint: "32", answers: ["32", "trente-deux"] },
  { theme: "Médecine", emoji: "💉", question: "Qui a inventé le vaccin contre la variole ?", hint: "Edward ...", answers: ["edward jenner", "jenner"] },
  { theme: "Médecine", emoji: "🩺", question: "Quel est l'organe le plus grand du corps humain ?", hint: "On l'oublie souvent", answers: ["peau"] },

  // ===== FAITS SURPRENANTS =====
  { theme: "Fun Facts", emoji: "🤔", question: "Combien de temps dure la journée sur Vénus (en jours terrestres) ?", hint: "Plus long qu'une année vénusienne", answers: ["243", "243 jours"] },
  { theme: "Fun Facts", emoji: "🤯", question: "Combien de cœurs a un poulpe ?", hint: "Trois", answers: ["3", "trois"] },
  { theme: "Fun Facts", emoji: "🤔", question: "Quel est le seul pays sans capitale officielle ?", hint: "Nauru", answers: ["nauru"] },
  { theme: "Fun Facts", emoji: "🤯", question: "Combien d'os a un requin ?", hint: "Zéro", answers: ["0", "zero", "zéro", "aucun"] },
  { theme: "Fun Facts", emoji: "🤔", question: "Quel est l'animal le plus dangereux pour l'homme ?", hint: "Insecte porteur de maladies", answers: ["moustique"] },
  { theme: "Fun Facts", emoji: "🤯", question: "Combien de fois la Lune tient-elle dans le Soleil ?", hint: "Environ 64 millions", answers: ["64 millions", "64000000"] },
  { theme: "Fun Facts", emoji: "🤔", question: "Quel est le seul mammifère qui ne peut pas sauter ?", hint: "Le plus grand terrestre", answers: ["elephant", "éléphant"] },

  // ===== SPORT SUPPLÉMENTAIRE =====
  { theme: "Sport", emoji: "⚾", question: "Combien de balles pour un 'walk' au baseball ?", hint: "4 balles", answers: ["4", "quatre"] },
  { theme: "Sport", emoji: "🏉", question: "Dans quel sport le ballon est-il ovale ?", hint: "Rugby ou ...", answers: ["rugby", "football americain", "american football"] },
  { theme: "Sport", emoji: "🏸", question: "Quel sport utilise un volant ?", hint: "Badminton", answers: ["badminton"] },
  { theme: "Sport", emoji: "⛷️", question: "Dans quelle ville ont eu lieu les JO d'hiver de 1992 ?", hint: "En France, Alpes", answers: ["albertville"] },
  { theme: "Sport", emoji: "🥋", question: "Dans quel sport pratique-t-on le 'kumite' ?", hint: "Art martial japonais", answers: ["karate", "karaté"] },
  { theme: "Sport", emoji: "🏊", question: "Quelle est la longueur d'une piscine olympique ?", hint: "50 mètres", answers: ["50 metres", "50m", "50 m"] },
  { theme: "Sport", emoji: "⚽", question: "Quelle équipe française a remporté la Ligue des Champions en 1993 ?", hint: "Club phocéen", answers: ["marseille", "olympique de marseille", "om"] },
  { theme: "Sport", emoji: "🎾", question: "Quelle surface est utilisée à Roland-Garros ?", hint: "Terre ...", answers: ["terre battue"] },

  // ===== CINÉMA SUPPLÉMENTAIRE =====
  { theme: "Cinéma", emoji: "🎬", question: "Quel film de 1975 de Spielberg a rendu les gens terrifiés de la mer ?", hint: "Requin blanc", answers: ["les dents de la mer", "jaws"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue dans 'Fight Club' et 'Se7en' ?", hint: "Brad ...", answers: ["brad pitt", "pitt"] },
  { theme: "Cinéma", emoji: "🎬", question: "Dans quel film voit-on 'Il était une fois dans l'Ouest' de Leone ?", hint: "Le titre du film", answers: ["il etait une fois dans l'ouest", "once upon a time in the west"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel studio a créé les films 'Toy Story', 'Cars' et 'Up' ?", hint: "Pixar", answers: ["pixar"] },
  { theme: "Cinéma", emoji: "🎬", question: "Quel acteur joue Jack Sparrow dans 'Pirates des Caraïbes' ?", hint: "Johnny ...", answers: ["johnny depp", "depp"] },

  // ===== MUSIQUE SUPPLÉMENTAIRE =====
  { theme: "Musique", emoji: "🎵", question: "Quel groupe chante 'Smells Like Teen Spirit' ?", hint: "Kurt Cobain", answers: ["nirvana"] },
  { theme: "Musique", emoji: "🎸", question: "Comment s'appelle le chanteur du groupe U2 ?", hint: "Bono", answers: ["bono"] },
  { theme: "Musique", emoji: "🎵", question: "Quelle chanteuse a sorti l'album 'Lemonade' en 2016 ?", hint: "Queen Bey", answers: ["beyonce", "beyoncé"] },
  { theme: "Musique", emoji: "🎹", question: "Comment s'appelle l'opéra le plus connu de Mozart ?", hint: "La flûte enchantée", answers: ["la flute enchantee", "la flûte enchantée", "magic flute"] },
  { theme: "Musique", emoji: "🎤", question: "Qui a sorti l'album 'Thriller' (1982) ?", hint: "Michael ...", answers: ["michael jackson", "jackson"] },
  { theme: "Musique", emoji: "🥁", question: "Quel est l'instrument le plus grave d'un orchestre ?", hint: "Contrebasse", answers: ["contrebasse"] },

  // ===== PAYS ET DRAPEAUX =====
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau avec une feuille d'érable rouge ?", hint: "Amérique du Nord", answers: ["canada"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau blanc et rouge ?", hint: "Plusieurs possibilités... La Pologne", answers: ["pologne", "poland"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau tricolore bleu, blanc, rouge ?", hint: "Pays des droits de l'homme", answers: ["france"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau avec une Union Jack ?", hint: "Royaume-Uni", answers: ["royaume-uni", "uk", "angleterre", "grande-bretagne"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau avec le soleil et l'aigle ?", hint: "Mexique", answers: ["mexique", "mexico"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau avec un croissant et une étoile ?", hint: "Pays musulman d'Asie", answers: ["turquie", "turkey", "pakistan"] },
  { theme: "Drapeaux", emoji: "🚩", question: "De quel pays est le drapeau rouge avec un cercle blanc ?", hint: "Japon", answers: ["japon", "japan"] },
];

module.exports = questions;
